package com.embabel.learning.common.domain;

import com.fasterxml.jackson.annotation.JsonPropertyDescription;

/**
 * Shared story payload used across Write/Review and RepeatUntil lessons.
 *
 * @param text story body generated by an LLM action
 */
public record Story(
        @JsonPropertyDescription("The full text of the story")
        String text
) {
}
